made new todo page responsive and added ability to visualize selected…
solidtm/Todo_List_App_Android pull request #1
Opened 2022-10-24 22:50 UTC by adexfit

made new todo page responsive and added ability to visualize selected todo category and priority button, edited home fragment for responsiveness

2022-10-25 13:00 UTC, solidtm requested changes

2022-10-25 13:00 UTC, solidtm commented on app/src/main/java/com/solid/todolistapp/features/task/NewTodoActivity.kt
> +        }
Hi @adexfit great Job you did here, I love how you thought about implementing the changes I mentioned. 
We still have a little more fixes to do: 

1. There would be no need to override onClick() function here any more, and the same thing can be achieved on the button onClickListener. Hence, remove this overidden onClick() function and create a function named setUpListeners and move this code s in the onClick(), but this time using view binding instead.

2. You are doing a lot of work on the UI thread inside this changeActiveBtnColor() function. 
So when we talked about functions in Kotlin, I thought you about extension functions. Create a general extension function on a View or Button that sets the textColor and backgroundColor, and use that for the different when conditions.

2022-10-25 13:02 UTC, solidtm commented on app/src/main/java/com/solid/todolistapp/features/task/NewTodoActivity.kt
> +        }
If you have any further questions, please don't hesitate to drop  in this thread, so we fast track.

2022-10-25 18:14 UTC, solidtm commented on app/src/main/java/com/solid/todolistapp/features/task/NewTodoActivity.kt
> +        }
This is an example: 

fun View.visibleIf(show: Boolean?) {
    visibility = if (show == true) View.VISIBLE
    else View.GONE
}

fun View.setColor(check: Boolean?, @ColorRes checkedColor: Int, @ColorRes uncheckedColor: Int) {
    if (check == true) {
        setBackgroundColor(ContextCompat.getColor(context, checkedColor))
    } else setBackgroundColor(ContextCompat.getColor(context, uncheckedColor))
}

fun View.setTColor(check: Boolean?, @ColorRes checkedColor: Int, @ColorRes uncheckedColor: Int) {
    if (check == true) {
        (ContextCompat.getColor(context, checkedColor))
    } else setBackgroundColor(ContextCompat.getColor(context, uncheckedColor))
}

fun View.show() {
    visibility = View.VISIBLE
}

fun View.gone() {
    visibility = View.GONE
}

2022-10-28 17:00 UTC, adexfit commented
I have made the changes sir

2022-10-28 17:49 UTC, merged